import { Question } from "../models/question";

export const HARDCODED_QUESTIONS: Question[] = [
    {
        id: 79,
        question_text: "When was the Declaration of Independence adopted?",
        acceptable_answers: ["July 4, 1776"],
        acceptable_answers_norm: ["july41776"],
        is_65_20_starred: false,
        category: "american_history",
        grading_mode: "exact",
        answer_type: "static",
        uscis_civics_questions_version: "2025",
    },
    { 
        id: 77,
        question_text: "Name one reason why the Americans declared independence from Britain?",
        acceptable_answers: [
            "High taxes",
            "Taxation without representation", 
            "Quartering of troops", 
            "British military presence"
        ],
        acceptable_answers_norm: [
            "hightaxes", 
            "taxationwithoutrepresentation", 
            "quarteringoftroops", 
            "britishmilitarypresence"
        ],
        is_65_20_starred: false,
        category: "american_history",
        grading_mode: "one_of",
        answer_type: "static",
        uscis_civics_questions_version: "2025",
    },
    {
        id: 123,
        question_text: "What is the name of the national anthem?",
        acceptable_answers: ["The Star-Spangled Banner", "Star-Spangled Banner"],
        acceptable_answers_norm: ["thestarspangledbanner", "starspangledbanner"],
        is_65_20_starred: false,
        category: "symbols_and_holidays",
        grading_mode: "exact",
        answer_type: "static",
        uscis_civics_questions_version: "2025",
    },{ 
        id: 81,
        question_text: "There were 13 original states. Name five.",
        acceptable_answers: [
            "New Hampshire",
            "New York",
            "New Jersey",
            "Delaware",
            "Pennsylvania",
            "Massachusetts",
            "Connecticut",
            "Rhode Island",
            "Maryland",
            "Virginia",
            "North Carolina",
            "South Carolina",
            "Georgia"
        ],
        acceptable_answers_norm: [
            "newhampshire",
            "newyork",
            "newjersey",
            "delaware",
            "pennsylvania",
            "massachusetts",
            "connecticut",
            "rhodeisland",
            "maryland",
            "virginia",
            "northcarolina",
            "southcarolina",
            "georgia"
        ],
        is_65_20_starred: false,
        category: "american_history",
        grading_mode: "multi",
        answer_type: "static",
        uscis_civics_questions_version: "2025",
    },
    {
        id: 78,
        question_text: "Who wrote the Declaration of Independence?",
        acceptable_answers: ["Thomas Jefferson", "Jefferson"],
        acceptable_answers_norm: ["thomasjefferson", "jefferson"],
        is_65_20_starred: true,
        category: "american_history",
        grading_mode: "exact",
        answer_type: "static",
        uscis_civics_questions_version: "2025",
    },
    {
        id: 39,
        question_text: "What is the name of the Vice President now?",
        acceptable_answers: ["JD Vance", "Vance"],
        acceptable_answers_norm: ["jdvance", "vance"],
        is_65_20_starred: true,
        category: "american_government",
        grading_mode: "exact",
        answer_type: "dynamic_official",
        uscis_civics_questions_version: "2025",
    },
    {
        id: 29,
        question_text: "Name your US Representative.",
        acceptable_answers: ["Lateefah Simon", "Simon"],
        acceptable_answers_norm: ["lateefahsimon", "simon"],
        is_65_20_starred: false,
        category: "american_government",
        grading_mode: "exact",
        answer_type: "state_specific",
        uscis_civics_questions_version: "2025",
    }

];